/*
Variable: Variable are the named container that stores data;
as an example : let name="Nirab";
here name is the variable and Nirab the stored value which is a string;

and also

let age=21;

here age is the variable and 21 is the data stored in it

Rules for Naming Variable;

1). Case Sensitivity: To Give a name to variable you must know this rule of case sensetivity or else it will create a high chances of error;
Example: 
let age=21;
and
let Age=21;
these are the different things in Js

2). Letter number underscore and /"$/" is allowed while naming

3).First Char should alphabet or a num or a underscore /"_/" or a /"$/";

4).Reserve word cant be used for naming the variable

5).Camel Case is Followed :-
Example:
let myArray=[" "," "]

*/